In [51]:
import pandas as pd
import os

In [79]:
if os.path.isdir('../raw_data') == False:
    os.mkdir('../raw_data')

True

In [52]:
data = pd.read_csv ('train.csv')

In [53]:
data['Time'] = pd.to_datetime(data['timestamp'], unit='s')

In [54]:
asset_details = pd.read_csv('asset_details.csv')

In [55]:
data.head(10)

,timestamp,Asset_ID,Count,Open,High,Low,Close,Volume,VWAP,Target,Time
0,1514764860,2,40.0,2376.580000,2399.5000,2357.1400,2374.590000,19.233005,2373.116392,-0.004218,2018-01-01 00:01:00
1,1514764860,0,5.0,8.530000,8.5300,8.5300,8.530000,78.380000,8.530000,-0.014399,2018-01-01 00:01:00
2,1514764860,1,229.0,13835.194000,14013.8000,13666.1100,13850.176000,31.550062,13827.062093,-0.014643,2018-01-01 00:01:00
3,1514764860,5,32.0,7.659600,7.6596,7.6567,7.657600,6626.713370,7.657713,-0.013922,2018-01-01 00:01:00
4,1514764860,7,5.0,25.920000,25.9200,25.8740,25.877000,121.087310,25.891363,-0.008264,2018-01-01 00:01:00
5,1514764860,6,173.0,738.302500,746.0000,732.5100,738.507500,335.987856,738.839291,-0.004809,2018-01-01 00:01:00
6,1514764860,9,167.0,225.330000,227.7800,222.9800,225.206667,411.896642,225.197944,-0.009791,2018-01-01 00:01:00
7,1514764860,11,7.0,329.090000,329.8800,329.0900,329.460000,6.635710,329.454118,NaN,2018-01-01 00:01:00
8,1514764920,2,53.0,2374.553333,2400.9000,2354.2000,2372.286667,24.050259,2371.434498,-0.004079,2018-01-01 00:02:00
9,1514764920,0,7.0,8.530000,8.5300,8.5145,8.514500,71.390000,8.520215,-0.015875,2018-01-01 00:02:00

In [56]:
asset_details.head(15)

    Asset_ID    Weight        Asset_Name
0          0  4.304065      Binance Coin
1          1  6.779922           Bitcoin
2          2  2.397895      Bitcoin Cash
3          3  4.406719           Cardano
4          4  3.555348          Dogecoin
5          5  1.386294            EOS.IO
6          6  5.894403          Ethereum
7          7  2.079442  Ethereum Classic
8          8  1.098612              IOTA
9          9  2.397895          Litecoin
10        10  1.098612             Maker
11        11  1.609438            Monero
12        12  2.079442           Stellar
13        13  1.791759              TRON

In [57]:
asset_list = []

for each in asset_details['Asset_ID']:
    print(each)
    asset_list.append( pd.DataFrame(data.loc[data['Asset_ID'] == each ]) )

0
1
2
3
4
5
6
7
8
9
10
11
12
13

In [58]:
count = 0

for each in asset_list:
    print (count, ")   ", asset_list[count].shape[0])
    count = count + 1

0 )    1942619
1 )    1956282
2 )    1953537
3 )    1791867
4 )    1156866
5 )    1955140
6 )    1956200
7 )    1951127
8 )    1592071
9 )    1956030
10 )    670497
11 )    1701261
12 )    1778749
13 )    1874560

In [59]:
BTC_data = pd.DataFrame(asset_list[1])
ETH_data = pd.DataFrame(asset_list[6])

In [60]:
BTC_data.tail(20)

,timestamp,Asset_ID,Count,Open,High,Low,Close,Volume,VWAP,Target,Time
24236529,1632181260,1,2281.0,42718.815000,42819.380000,42690.84,42781.970571,76.339988,42755.785162,0.003246,2021-09-20 23:41:00
24236543,1632181320,1,2642.0,42772.921250,42827.100000,42690.75,42755.592500,117.429123,42749.075916,0.003108,2021-09-20 23:42:00
24236557,1632181380,1,2134.0,42762.290000,42811.300000,42694.37,42717.234286,78.049458,42749.024591,0.002770,2021-09-20 23:43:00
24236571,1632181440,1,2165.0,42703.802500,42752.000000,42636.76,42657.202500,86.518794,42680.263993,0.002726,2021-09-20 23:44:00
24236585,1632181500,1,2177.0,42655.528484,42715.990000,42630.17,42678.721429,93.523647,42679.036829,NaN,2021-09-20 23:45:00
24236599,1632181560,1,2352.0,42688.935000,42810.260000,42662.27,42778.291250,97.442472,42739.891567,NaN,2021-09-20 23:46:00
24236613,1632181620,1,2080.0,42790.287143,42828.000000,42742.36,42790.175714,97.634234,42794.666167,NaN,2021-09-20 23:47:00
24236627,1632181680,1,2058.0,42792.855714,42827.700000,42713.48,42731.731429,78.468814,42786.068940,NaN,2021-09-20 23:48:00
24236641,1632181740,1,3717.0,42745.153750,42937.310000,42713.48,42898.565000,116.567006,42828.789861,NaN,2021-09-20 23:49:00
24236655,1632181800,1,3253.0,42896.174286,42966.980000,42852.07,42939.645714,113.220529,42910.257438,NaN,2021-09-20 23:50:00
24236669,1632181860,1,2264.0,42937.784286,42971.950000,42899.10,42927.167143,56.655507,42932.332787,NaN,2021-09-20 23:51:00
24236683,1632181920,1,2824.0,42933.254907,43014.980000,42907.18,42979.833750,97.404745,42963.462903,NaN,2021-09-20 23:52:00
24236697,1632181980,1,1697.0,42974.108693,43005.650000,42929.74,42960.601429,58.419459,42963.080444,NaN,2021-09-20 23:53:00
24236711,1632182040,1,1439.0,42971.347143,43008.850000,42953.10,42985.482857,39.329753,42981.323152,NaN,2021-09-20 23:54:00
24236725,1632182100,1,1608.0,42982.915714,43006.540000,42958.06,42985.214824,47.701279,42983.752149,NaN,2021-09-20 23:55:00
24236739,1632182160,1,1940.0,42983.780000,43001.850849,42878.26,42899.012857,56.850913,42935.489499,NaN,2021-09-20 23:56:00
24236753,1632182220,1,2026.0,42904.197143,42932.000000,42840.16,42860.005714,80.993326,42879.576084,NaN,2021-09-20 23:57:00
24236767,1632182280,1,1986.0,42859.385714,42887.500000,42797.20,42827.020000,65.677734,42844.090693,NaN,2021-09-20 23:58:00
24236781,1632182340,1,4047.0,42839.012802,43042.160000,42818.10,43017.277143,138.335477,42935.761938,NaN,2021-09-20 23:59:00
24236795,1632182400,1,2698.0,43009.961250,43048.510000,42961.64,43002.505000,128.206820,43011.414052,NaN,2021-09-21 00:00:00

In [61]:
start_date_train = '2018-01-01 00:00:00'
end_date_train = '2021-01-01 00:00:00'

In [62]:
start_date_test = '2021-01-01 00:00:00'
end_date_test = '2021-09-01 00:00:00'

In [63]:
### MIN TEST and TRAIN RAW DATA

In [64]:
#BTC MIN Train

mask = (BTC_data['Time'] > start_date_train) & (BTC_data['Time'] <= end_date_train)

BTC_data_trim_train_min = pd.DataFrame(BTC_data.loc[mask])

BTC_data_trim_train_min.drop('Target', inplace=True, axis=1)

BTC_data_trim_train_min = BTC_data_trim_train_min.reset_index(drop=True)

BTC_data_trim_train_min.to_csv('../raw_data/BTC_min_train.csv')

In [65]:
#BTC MIN Test

mask = (BTC_data['Time'] > start_date_test) & (BTC_data['Time'] <= end_date_test)

BTC_data_trim_test_min = pd.DataFrame(BTC_data.loc[mask])

BTC_data_trim_test_min.drop('Target', inplace=True, axis=1)

BTC_data_trim_test_min = BTC_data_trim_test_min.reset_index(drop=True)

BTC_data_trim_test_min.to_csv('../raw_data/BTC_min_test.csv')

In [66]:
#ETH MIN Train

mask = (ETH_data['Time'] > start_date_train) & (ETH_data['Time'] <= end_date_train)

ETH_data_trim_train_min = pd.DataFrame(ETH_data.loc[mask])

ETH_data_trim_train_min.drop('Target', inplace=True, axis=1)

ETH_data_trim_train_min = ETH_data_trim_train_min.reset_index(drop=True)

ETH_data_trim_train_min.to_csv('../raw_data/ETH_min_train.csv')

In [67]:
#ETH MIN Test

mask = (ETH_data['Time'] > start_date_test) & (ETH_data['Time'] <= end_date_test)

ETH_data_trim_test_min = pd.DataFrame(ETH_data.loc[mask])

ETH_data_trim_test_min.drop('Target', inplace=True, axis=1)

ETH_data_trim_test_min = ETH_data_trim_test_min.reset_index(drop=True)

ETH_data_trim_test_min.to_csv('../raw_data/ETH_min_test.csv')

In [68]:
### HOUR TEST and TRAIN RAW DATA

In [69]:
#BTC HOUR Train

#BTC DAY Train

mask = (BTC_data['Time'] > start_date_train) & (BTC_data['Time'] <= end_date_train)

BTC_data_trim_train_hour = pd.DataFrame(BTC_data.loc[mask])

BTC_data_trim_train_hour.drop('Target', inplace=True, axis=1)

BTC_data_trim_train_hour = BTC_data_trim_train_hour.reset_index(drop=True)


vol_list = []
count_list = []
sum_vol = 0
sum_count = 0
for each in range(0, BTC_data_trim_train_hour.shape[0]):
    if BTC_data_trim_train_hour['timestamp'].values[each] % 3600 != 0:
        sum_vol = sum_vol + BTC_data_trim_train_hour['Volume'].values[each]
        sum_count = sum_count + BTC_data_trim_train_hour['Count'].values[each]
    else:
        vol_list.append(sum_vol)
        count_list.append(sum_count)
        sum_vol = 0
        sum_count = 0
    


temp = BTC_data_trim_train_hour.loc[BTC_data_trim_train_hour['timestamp'] % 3600 == 0]

BTC_data_trim_train_hour = temp

BTC_data_trim_train_hour = BTC_data_trim_train_hour.reset_index(drop=True)

BTC_data_trim_train_hour.drop(columns=['Volume', 'Count'])

BTC_data_trim_train_hour['Volume'] = vol_list
BTC_data_trim_train_hour['Count'] = count_list

BTC_data_trim_train_hour

BTC_data_trim_train_hour.to_csv('../raw_data/BTC_hour_train.csv')

In [70]:
#BTC HOUR Test

#BTC DAY Test

mask = (BTC_data['Time'] > start_date_test) & (BTC_data['Time'] <= end_date_test)

BTC_data_trim_test_hour = pd.DataFrame(BTC_data.loc[mask])

BTC_data_trim_test_hour.drop('Target', inplace=True, axis=1)

BTC_data_trim_test_hour = BTC_data_trim_test_hour.reset_index(drop=True)


vol_list = []
count_list = []
sum_vol = 0
sum_count = 0
for each in range(0, BTC_data_trim_test_hour.shape[0]):
    if BTC_data_trim_test_hour['timestamp'].values[each] % 3600 != 0:
        sum_vol = sum_vol + BTC_data_trim_test_hour['Volume'].values[each]
        sum_count = sum_count + BTC_data_trim_test_hour['Count'].values[each]
    else:
        vol_list.append(sum_vol)
        count_list.append(sum_count)
        sum_vol = 0
        sum_count = 0
    


temp = BTC_data_trim_test_hour.loc[BTC_data_trim_test_hour['timestamp'] % 3600 == 0]

BTC_data_trim_test_hour = temp

BTC_data_trim_test_hour = BTC_data_trim_test_hour.reset_index(drop=True)

BTC_data_trim_test_hour.drop(columns=['Volume', 'Count'])

BTC_data_trim_test_hour['Volume'] = vol_list
BTC_data_trim_test_hour['Count'] = count_list

BTC_data_trim_test_hour

BTC_data_trim_test_hour.to_csv('../raw_data/BTC_hour_test.csv')

In [71]:
#ETH HOUR Train

mask = (ETH_data['Time'] > start_date_train) & (ETH_data['Time'] <= end_date_train)

ETH_data_trim_train_hour = pd.DataFrame(ETH_data.loc[mask])

ETH_data_trim_train_hour.drop('Target', inplace=True, axis=1)

ETH_data_trim_train_hour = ETH_data_trim_train_hour.reset_index(drop=True)


vol_list = []
count_list = []
sum_vol = 0
sum_count = 0
for each in range(0, ETH_data_trim_train_hour.shape[0]):
    if ETH_data_trim_train_hour['timestamp'].values[each] % 3600 != 0:
        sum_vol = sum_vol + ETH_data_trim_train_hour['Volume'].values[each]
        sum_count = sum_count + ETH_data_trim_train_hour['Count'].values[each]
    else:
        vol_list.append(sum_vol)
        count_list.append(sum_count)
        sum_vol = 0
        sum_count = 0
    


temp = ETH_data_trim_train_hour.loc[ETH_data_trim_train_hour['timestamp'] % 3600 == 0]

ETH_data_trim_train_hour = temp

ETH_data_trim_train_hour = ETH_data_trim_train_hour.reset_index(drop=True)

ETH_data_trim_train_hour.drop(columns=['Volume', 'Count'])

ETH_data_trim_train_hour['Volume'] = vol_list
ETH_data_trim_train_hour['Count'] = count_list

ETH_data_trim_train_hour

ETH_data_trim_train_hour.to_csv('../raw_data/ETH_hour_train.csv')

In [72]:
#ETH HOUR Test

mask = (ETH_data['Time'] > start_date_test) & (ETH_data['Time'] <= end_date_test)

ETH_data_trim_test_hour = pd.DataFrame(ETH_data.loc[mask])

ETH_data_trim_test_hour.drop('Target', inplace=True, axis=1)

ETH_data_trim_test_hour = ETH_data_trim_test_hour.reset_index(drop=True)


vol_list = []
count_list = []
sum_vol = 0
sum_count = 0
for each in range(0, ETH_data_trim_test_hour.shape[0]):
    if ETH_data_trim_test_hour['timestamp'].values[each] % 3600 != 0:
        sum_vol = sum_vol + ETH_data_trim_test_hour['Volume'].values[each]
        sum_count = sum_count + ETH_data_trim_test_hour['Count'].values[each]
    else:
        vol_list.append(sum_vol)
        count_list.append(sum_count)
        sum_vol = 0
        sum_count = 0
    


temp = ETH_data_trim_test_hour.loc[ETH_data_trim_test_hour['timestamp'] % 3600 == 0]

ETH_data_trim_test_hour = temp

ETH_data_trim_test_hour = ETH_data_trim_test_hour.reset_index(drop=True)

ETH_data_trim_test_hour.drop(columns=['Volume', 'Count'])

ETH_data_trim_test_hour['Volume'] = vol_list
ETH_data_trim_test_hour['Count'] = count_list

ETH_data_trim_test_hour

ETH_data_trim_test_hour.to_csv('../raw_data/ETH_hour_test.csv')

In [73]:
### DAY TEST and TRAIN RAW DATA

In [74]:
#BTC DAY Train

mask = (BTC_data['Time'] > start_date_train) & (BTC_data['Time'] <= end_date_train)

BTC_data_trim_train_day = pd.DataFrame(BTC_data.loc[mask])

BTC_data_trim_train_day.drop('Target', inplace=True, axis=1)

BTC_data_trim_train_day = BTC_data_trim_train_day.reset_index(drop=True)


vol_list = []
count_list = []
sum_vol = 0
sum_count = 0
for each in range(0, BTC_data_trim_train_day.shape[0]):
    if BTC_data_trim_train_day['timestamp'].values[each] % 86400 != 0:
        sum_vol = sum_vol + BTC_data_trim_train_day['Volume'].values[each]
        sum_count = sum_count + BTC_data_trim_train_day['Count'].values[each]
    else:
        vol_list.append(sum_vol)
        count_list.append(sum_count)
        sum_vol = 0
        sum_count = 0
    


temp = BTC_data_trim_train_day.loc[BTC_data_trim_train_day['timestamp'] % 86400 == 0]

BTC_data_trim_train_day = temp

BTC_data_trim_train_day = BTC_data_trim_train_day.reset_index(drop=True)

BTC_data_trim_train_day.drop(columns=['Volume', 'Count'])

BTC_data_trim_train_day['Volume'] = vol_list
BTC_data_trim_train_day['Count'] = count_list

BTC_data_trim_train_day

BTC_data_trim_train_day.to_csv('../raw_data/BTC_day_train.csv')

In [75]:
#BTC DAY Test

mask = (BTC_data['Time'] > start_date_test) & (BTC_data['Time'] <= end_date_test)

BTC_data_trim_test_day = pd.DataFrame(BTC_data.loc[mask])

BTC_data_trim_test_day.drop('Target', inplace=True, axis=1)

BTC_data_trim_test_day = BTC_data_trim_test_day.reset_index(drop=True)


vol_list = []
count_list = []
sum_vol = 0
sum_count = 0
for each in range(0, BTC_data_trim_test_day.shape[0]):
    if BTC_data_trim_test_day['timestamp'].values[each] % 86400 != 0:
        sum_vol = sum_vol + BTC_data_trim_test_day['Volume'].values[each]
        sum_count = sum_count + BTC_data_trim_test_day['Count'].values[each]
    else:
        vol_list.append(sum_vol)
        count_list.append(sum_count)
        sum_vol = 0
        sum_count = 0
    


temp = BTC_data_trim_test_day.loc[BTC_data_trim_test_day['timestamp'] % 86400 == 0]

BTC_data_trim_test_day = temp

BTC_data_trim_test_day = BTC_data_trim_test_day.reset_index(drop=True)

BTC_data_trim_test_day.drop(columns=['Volume', 'Count'])

BTC_data_trim_test_day['Volume'] = vol_list
BTC_data_trim_test_day['Count'] = count_list

BTC_data_trim_test_day

BTC_data_trim_test_day.to_csv('../raw_data/BTC_day_test.csv')

In [76]:
#ETH DAY Train

mask = (ETH_data['Time'] > start_date_train) & (ETH_data['Time'] <= end_date_train)

ETH_data_trim_train_day = pd.DataFrame(ETH_data.loc[mask])

ETH_data_trim_train_day.drop('Target', inplace=True, axis=1)

ETH_data_trim_train_day = ETH_data_trim_train_day.reset_index(drop=True)


vol_list = []
count_list = []
sum_vol = 0
sum_count = 0
for each in range(0, ETH_data_trim_train_day.shape[0]):
    if ETH_data_trim_train_day['timestamp'].values[each] % 86400 != 0:
        sum_vol = sum_vol + ETH_data_trim_train_day['Volume'].values[each]
        sum_count = sum_count + ETH_data_trim_train_day['Count'].values[each]
    else:
        vol_list.append(sum_vol)
        count_list.append(sum_count)
        sum_vol = 0
        sum_count = 0
    


temp = ETH_data_trim_train_day.loc[ETH_data_trim_train_day['timestamp'] % 86400 == 0]

ETH_data_trim_train_day = temp

ETH_data_trim_train_day = ETH_data_trim_train_day.reset_index(drop=True)

ETH_data_trim_train_day.drop(columns=['Volume', 'Count'])

ETH_data_trim_train_day['Volume'] = vol_list
ETH_data_trim_train_day['Count'] = count_list

ETH_data_trim_train_day

ETH_data_trim_train_day.to_csv('../raw_data/ETH_day_train.csv')

In [77]:
#ETH DAY Test

mask = (ETH_data['Time'] > start_date_test) & (ETH_data['Time'] <= end_date_test)

ETH_data_trim_test_day = pd.DataFrame(ETH_data.loc[mask])

ETH_data_trim_test_day.drop('Target', inplace=True, axis=1)

ETH_data_trim_test_day = ETH_data_trim_test_day.reset_index(drop=True)


vol_list = []
count_list = []
sum_vol = 0
sum_count = 0
for each in range(0, ETH_data_trim_test_day.shape[0]):
    if ETH_data_trim_test_day['timestamp'].values[each] % 86400 != 0:
        sum_vol = sum_vol + ETH_data_trim_test_day['Volume'].values[each]
        sum_count = sum_count + ETH_data_trim_test_day['Count'].values[each]
    else:
        vol_list.append(sum_vol)
        count_list.append(sum_count)
        sum_vol = 0
        sum_count = 0
    


temp = ETH_data_trim_test_day.loc[ETH_data_trim_test_day['timestamp'] % 86400 == 0]

ETH_data_trim_test_day = temp

ETH_data_trim_test_day = ETH_data_trim_test_day.reset_index(drop=True)

ETH_data_trim_test_day.drop(columns=['Volume', 'Count'])

ETH_data_trim_test_day['Volume'] = vol_list
ETH_data_trim_test_day['Count'] = count_list

ETH_data_trim_test_day

ETH_data_trim_test_day.to_csv('../raw_data/ETH_day_test.csv')